global:
  scrape_interval: 15s  # Définir la fréquence de scraping

scrape_configs:
  - job_name: 'myapi'
    scrape_interval: 5s  # Fréquence spécifique pour cette tâche
    static_configs:
      - targets: ['host.docker.internal:5000']  # L'adresse de votre API FastAPI
