apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    access: proxy
    editable: true

  - name: myapi-metrics
    type: prometheus
    url: http://myapi:5000
    access: proxy
    editable: true